### ISSUE TITLE
When you have time-dependent terms

### ISSUE THREAD

**Issue by rckirby** [firedrakeproject/Irksome#10]
When you have forcing terms depending on space and time, UFL interpolation is very slow.  It would be nice if somebody figured out how to fish out those terms and replace them with a projection/interpolation onto the right space for each stage of each time step.

**Comment by wence-** [comment]
Is this because you call `interpolate` every time, rather than building an `Interpolator`? This should go away with Connor's work.

**Comment by rckirby** [comment]
Actually, this was fixed at least as of us generalizing the BCs in #24
