### ISSUE TITLE
Dirichlet BCs don't work with explicit

### ISSUE THREAD

**Issue by ScottMacLachlan** [firedrakeproject/Irksome#102]
Strongly imposing Dirichlet BCs with `stage_type="explicit"` doesn't work.  Looking through the code, this seems obvious, since we have
```
                gdat /= dtc * float(AA[i, i])
```
[here](https://github.com/firedrakeproject/Irksome/blob/dc9f91cc9a1e4eac2f141e30a8de4400d4ef545f/irksome/dirk_stepper.py#L222C30-L222C46), which does bad things when `AA[i,i] == 0`.

Mathematically, I think we're just "off-by-one", in that our BC on `k[0]` should be derived from matching the BC at stage time `c[1]`, and so forth.  We need to think a bit about how to implement this in a non-intrusive way, though.

**Comment by pbrubeck** [comment]
I missed this file when I removed the gblah nonsense. That should also be dealt with

**Comment by ScottMacLachlan** [comment]
Yep - good point.  Would you be able to do that before we fix this?

**Comment by ScottMacLachlan** [comment]
I think the right fix for the explicit issue is to pull the loop that updates the BCs into a separate class method (presumably `update_bcs`).  Then, we can define an explicit-appropriate variant for the subclass (basically a careful off-by-one version of the current code, but keep the DIRK code as is

**Comment by pbrubeck** [comment]
DirichletBC is self-aware and does the right thing if you want to prescribe a time-dependent UFL expression. There should not be a need to manually update them.

**Comment by ScottMacLachlan** [comment]
This case is somewhat different than the others, since we're reusing the same solver for each stage, but the BCs change based on the computed solutions from the previous stages. So, I think we can't get away from an explicit update to the BCs before each stage, even if we do that in the more elegant way.  Does that make sense?

If so, I think that means that I can get rid of all the `gmethod` calls, and just do the updates directly based on `dat4bc(u0)` and `dat4bc(ks[j])`?

**Comment by ScottMacLachlan** [comment]
Thinking this through a bit more, I think the right solution is to just create a generic BC in the setup that depends on `Constant`s that represent the coefficients in the current row of the Butcher Table, and then just `assign` those constants to update with each row.
