### ISSUE TITLE
best way to assign a nullspace?

### ISSUE THREAD

**Issue by mwelland** [firedrakeproject/Irksome#23]
Hi, wondering what methods I can use to pass nullspace information about the system to the solver? I see some commented lines in the Navier Stokes demos but nothing implemented. Thanks!

**Comment by rckirby** [comment]
Thanks for the question.  There are some oversights in passing information from the `TimeStepper` class into the nonlinear solver.  My guess is that we should add an optional kwarg for the null space here:
https://github.com/firedrakeproject/Irksome/blob/8a52cd0d4b50432784a7f75eabea089449c58eed/irksome/stepper.py#L34

and then forward that into the variational solver here:
https://github.com/firedrakeproject/Irksome/blob/8a52cd0d4b50432784a7f75eabea089449c58eed/irksome/stepper.py#L50 

If you'd like to try it on a branch and make a PR, we'd welcome it!
