### ISSUE TITLE
push_parent in getForm

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/Irksome#33]
This https://github.com/firedrakeproject/Irksome/blob/63283f5d92ba99bc72cd9d9f1681ddea51f65bae/irksome/getForm.py#L188

Is almost certainly not the right place to do this. What you should do is push the parent in the solver and pop it off afterwards (otherwise every time getForm is called another parent is pushed).

**Comment by rckirby** [comment]
`getForm` is only called once per problem, so this should not a major issue but could be in a bigger application.  By "in the solver" do you mean having the user do it at the beginning/end of the time-step loop?  Hiding that detail might be done in a context manager?

**Comment by rckirby** [comment]
So one could do the push inside the `TimeStepper` constructor and then set up a `__del__` method to pop it.   This would hide it from the user.

Would that work?

**Comment by rckirby** [comment]
So how long does the  -- just for setting up the solver, just for calling the `solve` or does it need to be available for both?  The `TimeStepper` constructor sets up the `NLVS` and then its `advance` method calls `solve`.   This might inform whether we use a context manager to push/pop versus pushing during the  `TimeStepper` constructor and then setting up a destructor that pops.

**Comment by wence-** [comment]
I think it needs to be available for both. So you would in `__init__` say:

```
push_parent(V.dm, Vbig.dm)
self.solver = NLVS(...)
pop_parent(V.dm, Vbig.dm)
```

And similarly around the `self.solver.solve` call in `advance`.

**Comment by rckirby** [comment]
Ok, I did this and the tests all pass now.  Will do a PR.
