### ISSUE TITLE
Backward Euler Potential Bug?

### ISSUE THREAD

**Issue by medinaeder** [firedrakeproject/Irksome#34]
Solving an elastodynamics problem with backward Euler fails to update the velocity field.

Switching to QinZhang shows expected behavior.
[mfe.txt](https://github.com/firedrakeproject/Irksome/files/8406206/mfe.txt)

**Comment by rckirby** [comment]
I can certainly take a look at this.
A few questions/comments:
1.) You aren't using the `TimeStepper` class, or is doing that what triggers your problem?  BE lives in a special class of methods for which where there is an optimized routine for updating that might not be tested on products of vector-valued spaces.
2.) It will be easier for debugging to make your minimal example more minimal -- for example, checking the norm of the difference between your computed solution and the initial condition and raising an error if it's not changing, and you can probably demonstrate over a much shorter time interval, not generating output files, etc.  
3.) We certainly need to fix any errors in backward Euler... but you are probably aware that it's not the best method for this problem?  (QinZhang conserves energy, as well as GaussLegendre if you want higher accuracy and a more complicated linear system)

**Comment by medinaeder** [comment]
1.) I am not using `TimeStepper` because I was hoping to use time-dependent BCs. Using the seems like `TimeStepper` does not exhibit this behavior.
2.)  See attached. Simply observing the norm of the velocity after the first step shows that there is an error. Attached is another minimal version.
[mfev2.txt](https://github.com/firedrakeproject/Irksome/files/8411816/mfev2.txt)
3.) Yes. I was just kicking the irksome tires.  BE for some applications is often a  good enough choice because I don't have to think about adding extra damping terms.

**Comment by rckirby** [comment]
Time dependent `DirichletBC` are a thing in `TimeStepper` (that's the point of the whole `gmethod` bits you've ported over from inside the time-stepping).  This is tested here:
https://github.com/firedrakeproject/Irksome/blob/master/tests/test_inhomogbc.py
for the heat equation, and a demo for NSE is given here:
https://github.com/firedrakeproject/Irksome/blob/master/demos/navier_stokes/demo_nse_unsteady.py

If you think this meets your needs, let's close the issue and you can reopen it if you find something broken or not what you need.   If not, we can try to dig deeper in your mfev2 (which I can confirm now clearly displays the disturbing behavior) and see what's going wrong.  Updating the solution, especially for multiple stages and mixed problems is pretty subtle, so I really recommend using the public interface whenever you can.

**Comment by medinaeder** [comment]
Sounds good!
I was simply going off this [demo](https://firedrakeproject.github.io/Irksome/demos/demo_lowlevel_inhomogbc.py.html)
I thought they were time-dependent bcs required the use of a low-level interface.
